### ISSUE TITLE
Upload File from Disk -> MediaAlly

### ISSUE THREAD

**Issue by GLStephen** [cloudinary-community/cloudinary-laravel#108]
This fails because it's not an "SplFile" which supports "getRealPath", but the path there IS the real path.

```
$user->attachMedia(Storage::path($path), $file_name);
```

I'm trying to support Laraval Livewrire uploads which uploads to a temporary directory locally and then attach to a model and upload to Cloudinary.

This check: https://github.com/cloudinary-devs/cloudinary-laravel/blob/63400a9eab277bb2e0623feb5e1dc3c0bf0965a4/src/MediaAlly.php#L33

Seems incompatible with this: getRealPath call.

https://github.com/cloudinary-devs/cloudinary-laravel/blob/63400a9eab277bb2e0623feb5e1dc3c0bf0965a4/src/MediaAlly.php#L37

file_exists expects a string, while getRealPath expects an object.

**Comment by joshmanders** [comment]
Hello @GLStephen I have taken over maintaining this repo and I'm wondering if this is still an issue or have you resolved it or not? I can take a look at making this work if it doesn't already.

**Comment by joshmanders** [comment]
Closing. If this problem arrises again, please open a new issue.
