### ISSUE TITLE
Trait "League\Flysystem\Adapter\Polyfill\NotSupportingVisibilityTrait" not found

### ISSUE THREAD

**Issue by danielozeh** [cloudinary-community/cloudinary-laravel#114]
I am using `"cloudinary-labs/cloudinary-laravel": "^2.1"` but I get the above error message.

My flysystem version `"league/flysystem-aws-s3-v3": "^3.0"`

I have also attached a screenshot here.

Kindly help

Thanks
<img width="1673" alt="Screenshot 2024-06-07 at 22 02 27" src="https://github.com/cloudinary-community/cloudinary-laravel/assets/50729875/81ef579f-8a3c-4bae-a67e-86ea21485968">

**Comment by joshmanders** [comment]
Hello @danielozeh I published v2.2.0 yesterday which should make it work in Laravel 10 and 11. Go ahead and give it a try and if you see any problems, please open a new issue so I can address it.
