### ISSUE TITLE
No support for Laravel >=9.x: Is the package still maintained?

### ISSUE THREAD

**Issue by newtonjob** [cloudinary-community/cloudinary-laravel#116]
Been using this package for a long time, until I realized all my projects are suddenly breaking.

The package can no longer be used from Laravel >= 9.x which uses `league/flysystem` v3

`league/flysystem` has since moved to v3, but this `CloudinaryAdapter` still uses interfaces and traits from v1.

There are several other issues faced by other devs coming down to same problem, e.g.
- #112
- #83
- #114

I am willing to make PRs to update and generally improve the package, but need to know if we still got some eyes here?

**Comment by joshmanders** [comment]
Hey @newtonjob, I'm new to the project and have been tasked with bringing this up to date and fixing some bugs and adding new features. I apologize in advance if things look unmaintained as I ramp up and get familiar with the codebase!

**Comment by newtonjob** [comment]
Appreciate your response @joshmanders ❤️

**Comment by DmitrySidorenkoShim** [comment]
yes, it would be great to bring this package live again
and with Laravel 10.x too

because we are switching to Cloudinary very soon
and I need to use this package for our project 😌

**Comment by colbyfayock** [comment]
we should be cutting a compatibility release for v9 hopefully early this week and a v10+ release soon after!

**Comment by joshmanders** [comment]
> yes, it would be great to bring this package live again and with Laravel 10.x too
> 
> because we are switching to Cloudinary very soon and I need to use this package for our project 😌

I've cut a 1.0.6 release that makes it work with Laravel v9 again, this week I will be working on bringing it back to working state with bug fixes and tests to ensure no regressions including compatibility with Laravel 10 and 11.

**Comment by DmitrySidorenkoShim** [comment]
> > yes, it would be great to bring this package live again and with Laravel 10.x too
> > because we are switching to Cloudinary very soon and I need to use this package for our project 😌
> 
> I've cut a 1.0.6 release that makes it work with Laravel v9 again, this week I will be working on bringing it back to working state with bug fixes and tests to ensure no regressions including compatibility with Laravel 10 and 11.


excuse me, but it is still not working with Laravel 9.x 😌

I wanted to test upload feature with Statamic and 'cloudinary' disk
so, I've set up new Laravel project
Laravel v9.52.16
installed "cloudinary-labs/cloudinary-laravel": "1.0.6"
set up Statamic 4
and everything worked fine until create new asset container with 'cloudinary' disk

my colleague said that he was able to test this at the end of last year
but I have this error message now:

> Trait "League\Flysystem\Adapter\Polyfill\NotSupportingVisibilityTrait" not found

as you can see from screenshot below Laravel version is 9.x
![Screenshot 2024-07-30 at 16 47 29](https://github.com/user-attachments/assets/988d05cb-d8db-4ecf-9a07-c7f08dbd76a4)

what version have you used for v1.0.6?

**Comment by joshmanders** [comment]
@DmitrySidorenkoShim can you run `composer why league/flysystem` and tell me the output?

**Comment by DmitrySidorenkoShim** [comment]
here you go:
```
$composer why league/flysystem
laravel/framework      v9.52.16 requires league/flysystem (^3.8.0)    
league/flysystem-local 3.28.0   requires league/flysystem (^3.0.0)    
league/glide           2.3.0    requires league/flysystem (^2.0|^3.0)
```

**Comment by DmitrySidorenkoShim** [comment]
@joshmanders 

to be honest, it is not so important to have it working with Laravel 9.x right now
just wanted to check upload with flysystem Cloudinary adapter (and Statamic)

but crucial to have it working with Laravel 10.x as soon as possible
in the best case "yesterday" of course 😄
but next week would be really good too 
do you think it is possible?

**Comment by newtonjob** [comment]
@DmitrySidorenkoShim, if it works for Laravel 9.x, it believe it will also work for 10.x and 11.x

Primary issue is that these Laravel versions now use `league/flysystem` v3, but the package still uses v1

**Comment by joshmanders** [comment]
> @DmitrySidorenkoShim, if it works for Laravel 9.x, it believe it will also work for 10.x and 11.x
> 
> Primary issue is that these Laravel versions now use `league/flysystem` v3, but the package still uses v1

This is the issue, and I'm working on it @DmitrySidorenkoShim. See https://github.com/cloudinary-community/cloudinary-laravel/pull/123

**Comment by DmitrySidorenkoShim** [comment]
hi @joshmanders 

sorry for annoying you
but is there any good news? 😌

**Comment by joshmanders** [comment]
> hi @joshmanders
> 
> sorry for annoying you but is there any good news? 😌

Not annoying at all. Working through some stuff now and will hopefully have a release this weekend, Monday at the latest.

**Comment by DmitrySidorenkoShim** [comment]
hi @joshmanders 

I am just wondering if it isn’t ready yet? 😄

**Comment by newtonjob** [comment]
Huge thanks for your work on this @joshmanders!
