### ISSUE TITLE
During class fetch: Uncaught ParseError: syntax error, unexpected '|'

### ISSUE THREAD

**Issue by eli-easydoc** [cloudinary-community/cloudinary-laravel#119]
On version 1.0.6 that supposed to support PHP 7.X there is an argument declaration that is only supported on >PHP 8.X
cloudinary-labs/cloudinary-laravel/src/MediaAlly.php:87
`public function detachMedia(Collection|Media $media = null)`

**Comment by joshmanders** [comment]
Thank you @eli-easydoc. I will get this fixed and another version publish asap.

**Comment by joshmanders** [comment]
I just pushed a release for v1.0.7 which reverts back to v1.0.5 state.
