### ISSUE TITLE
Discrepancy file extention between upload and get the file

### ISSUE THREAD

**Issue by hamidroohani** [cloudinary-community/cloudinary-laravel#124]
When I upload an image into Cloudinary I will get `01J562MWE7WGBKVENZV50BYH39.jpg` as a result and put it into DB.
But when I want to check if file exists or not, or even show it, I must remove the file extension and call like:

```
\Illuminate\Support\Facades\Storage::disk('cloudinary')->exists("01J562MWE7WGBKVENZV50BYH39");
```

**Comment by colbyfayock** [comment]
@joshmanders just to provide some context on how the public IDs work, I'm not sure how the SDK is managing this, but the file extension is not required when constructing URLs

ex: res.cloudinary.com/.../publicid.jpg and res.cloudinary.com/.../publicid both work

I typically encourage not including it just for the sake of clarity, as you can additionally provide transformations to change that format, so having the extension can be confusing, but it's supported to be able to provide the extension, which i would have expected this to be handled by the underlaying PHP SDK depending on what this touches (as im not familiar)

thus, i would expect that this API would support both as well

**Comment by joshmanders** [comment]
I will look into this, thank you for the added context @colbyfayock
