### ISSUE TITLE
[Error] Return value must be of type array, Cloudinary\Api\ApiResponse returned

### ISSUE THREAD

**Issue by DmitrySidorenkoShim** [cloudinary-community/cloudinary-laravel#126]
hi @joshmanders 

since the last update to v2.2 yesterday
I have exception thrown

> CloudinaryLabs\CloudinaryLaravel\CloudinaryEngine::getResponse(): Return value must be of type array, Cloudinary\Api\ApiResponse returned

it is in `src/CloudinaryEngine.php` line 247

since it is declared as `array|ApiResponse`:

```
    /**
     *  Response from Cloudinary
     * @var array|ApiResponse
     */
    protected array|ApiResponse $response;
```
    
I think it makes sense to change `getResponse()` return type to the same
can you please do the fix asap?
thanks 😌

and I think it is much faster for you to change it
than for me to create fork and Pull Request
you would need to publish a new version anyway 😄

**Comment by joshmanders** [comment]
Published v2.2.1 that has this fix in it. Thanks! https://github.com/cloudinary-community/cloudinary-laravel/releases/tag/2.2.1
