### ISSUE TITLE
Unable to locate a class or view for component [cld-upload-button].

### ISSUE THREAD

**Issue by iamgoodbytes** [cloudinary-community/cloudinary-laravel#93]
Laravel 10 with latest version of this package running a livewire component that has the following code. (I'm getting the same error when using it in a normal blade file that is not a livewire component)

```
@cloudinaryJS
<x-cld-upload-button>
            Upload Files
</x-cld-upload-button>
```

Getting the error `Unable to locate a class or view for component [cld-upload-button].`

Any idea what could fix this or what the problem might be?

**Comment by miteyema** [comment]
I had the same problem and I've made a fix, please see https://github.com/cloudinary-devs/cloudinary-laravel/pull/94

**Comment by uhexos** [comment]
@unicodeveloper I see that PR #94 was merged to fix this issue, this means the documentation is now wrong as the component is called cld_upload_button rather than cld-upload-button

**Comment by unicodeveloper** [comment]
I wouldn’t say the documentation is wrong. The doc is still very much correct because most people don’t even use Laravel 6 anymore. 

So there’s really no need to update the doc. 

Changing the doc will make it wrong for Laravel 7 to 10 users & 99% of them are  using this package

**Comment by uhexos** [comment]
Maybe I'm doing something wrong then cause the widget wouldn't load and the `Unable to locate a class or view for component [cld-upload-button]` persisted in a fresh laravel 10 install when using the x-cld-upload-button as the component name.

![image](https://github.com/cloudinary-devs/cloudinary-laravel/assets/14164093/e26db7b8-7e8a-4b50-a61c-3772a6dbda9f)

**Comment by unicodeveloper** [comment]
That’s happening because I haven’t tagged a new release yet.

I’ll tag a new release by weekend that includes the most recent code merge

**Comment by uhexos** [comment]
ahh I see

**Comment by brammittendorff** [comment]
Is there already a new release? The last one is from march right?
